import ContentCtxProvider from "@/context/ContentContext"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "BitSaac | Portfolio",
  description: "Generated by create next app",
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return <ContentCtxProvider>{children}</ContentCtxProvider>
}
