import type { Metadata } from "next"
import { Inter, Roboto_Condensed } from "next/font/google"
import "./globals.scss"
// import Navbar from "@/components/navbar/Navbar"
import Navbar from "@/components/Navbar copy/Navbar"
import Footer from "@/components/footer/Footer"
import GotoTop from "@/components/GotoTop"
import { NavContextProvider } from "@/context/NavContext"

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
})
const roboto = Roboto_Condensed({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
})

export const metadata: Metadata = {
  title: "BITSAAC",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${roboto.variable}`}
    >
      <body>
        {children}

        <GotoTop />
      </body>
    </html>
  )
}
