import type { Metadata } from "next"
import { Inter, Roboto_Condensed } from "next/font/google"

import GotoTop from "@/components/GotoTop"
import "./globals.scss"
import { NextAuthProvider } from "./providers"

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
})
const roboto = Roboto_Condensed({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
})

export const metadata: Metadata = {
  title: "BITSAAC",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${roboto.variable}`}
    >
      <NextAuthProvider>
        <body>
          {children}
          <GotoTop />
        </body>
      </NextAuthProvider>
    </html>
  )
}
