import type { Metadata } from "next"

import GotoTop from "@/components/GotoTop"

export const metadata: Metadata = {
  title: "BITSAAC",
  description: "Generated by create next app",
}

export default function UploadLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {/* <Navbar /> */}
      {children}
      {/* <Footer /> */}
      <GotoTop />
    </>
  )
}
