import type { Metadata } from "next"

import GotoTop from "@/components/GotoTop"
import AdminNav from "@/components/admin/AdminNav"
import { auth, redirectToSignIn } from "@clerk/nextjs"
import FormContextProvider from "@/context/FormContext"

export const metadata: Metadata = {
  title: "Create",
  description: "Generated by create next app",
}

export default function UploadLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { userId } = auth()
  if (!userId) return redirectToSignIn()
  console.log(userId)
  return (
    <FormContextProvider>
      <AdminNav />
      <main className="max-container relative">{children}</main>
    </FormContextProvider>
  )
}
