import type { Metadata } from "next"

import GotoTop from "@/components/GotoTop"
import AdminNav from "@/components/admin/AdminNav"

export const metadata: Metadata = {
  title: "Create",
  description: "Generated by create next app",
}

export default function UploadLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <AdminNav />
      <main className="max-container relative">{children}</main>

      {/* <GotoTop /> */}
    </>
  )
}
